blank_issues_enabled: true
contact_links:
  - name: A security problem
    url: https://github.com/twidtwid/italiantranslate/security/advisories/new
    about: Please report it privately instead of in a public issue.
